package com.mygdx.shooter;


import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.Input.Keys;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.graphics.g2d.freetype.FreeTypeFontGenerator;
import com.badlogic.gdx.scenes.scene2d.Actor;
import com.badlogic.gdx.scenes.scene2d.Stage;
import com.badlogic.gdx.scenes.scene2d.ui.Dialog;
import com.badlogic.gdx.scenes.scene2d.ui.Image;
import com.badlogic.gdx.scenes.scene2d.ui.Label;
import com.badlogic.gdx.scenes.scene2d.ui.Skin;
import com.badlogic.gdx.scenes.scene2d.ui.Table;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton;
import com.badlogic.gdx.scenes.scene2d.ui.TextField;
import com.badlogic.gdx.scenes.scene2d.ui.Label.LabelStyle;
import com.badlogic.gdx.scenes.scene2d.ui.TextButton.TextButtonStyle;
import com.badlogic.gdx.scenes.scene2d.ui.TextField.TextFieldStyle;
import com.badlogic.gdx.scenes.scene2d.utils.Align;
import com.badlogic.gdx.scenes.scene2d.utils.ChangeListener;
import com.badlogic.gdx.utils.Scaling;


public class AddParticipant extends CustomScreen {
	
	private  FreeTypeFontGenerator generator = null;
	
	private Skin skin2 = null;
	private Skin textboxskin = null;
	private Skin skin;
	private TextureAtlas atlas = null;
    
	private BitmapFont button = null;
    private BitmapFont tLabel = null;
    private BitmapFont fLabel = null;
    private BitmapFont field = null;
    
    private	Texture uiButton = null;
    private	Texture uiCursor = null;
	
	private Stage stage;
	private Stage temp;
	
	private Label titleLabel;
	private Label sessionIDLabel;
	private Label playerIDLabel;
	
	private TextField sessionIDField;
	private TextField playerIDField;
	
	private TextButton confirm;
	private TextButton back;
	
	private Table table1;
	private Table mainTable;
	
	private String sessID;

    private OrthographicCamera camera;
    

    @SuppressWarnings("deprecation")	//suppresses deprecation warnings generated by "generateFont()"
	public AddParticipant() {
    	
    	setName("ADD_PARTICIPANT");		//Sets the current activity name
    	
    	//Implements the device's Back button functionality on current activity
    	temp = new Stage(){
    		@Override
	        public boolean keyDown(int keyCode) {
	            if (keyCode == Keys.BACK) {
	            	ScreenManager.getInstance().show("CONTROL_PANEL", Screens.CONTROL_PANEL);
	            }
	            return super.keyDown(keyCode);
    		}
    	};
    	setStage(temp);
    	stage = getStage();
    	
    	//Configures camera settings
        camera = new OrthographicCamera();
        camera.setToOrtho(false, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
              
        generator = ResourceManager.getGenerator();	//fetches font generator
        atlas = ResourceManager.getAtlas();			//fetches textureAtlas	
        skin = ResourceManager.getDefaultSkin();	//fetches default skin
        skin2 = ResourceManager.getCustomSkin();	//fetches customized skin
        
		button = generator.generateFont(Gdx.graphics.getWidth()/24);	//generates font size for button objects
        tLabel = generator.generateFont(Gdx.graphics.getWidth()/10);	//generates font size for title label objects
        fLabel = generator.generateFont(Gdx.graphics.getWidth()/25);	//generates font size for form label objects
        field = generator.generateFont(Gdx.graphics.getWidth()/40);		//generates font size for text fields objects
        
        LabelStyle titleSkin = new LabelStyle();
        titleSkin.font = tLabel;					//sets font size of the title's label style
        
        LabelStyle formLabelSkin = new LabelStyle();
        formLabelSkin.font = fLabel;				////sets font size of form label style
       
        //Configurations of text button style
        TextButtonStyle textButtonStyle = new TextButtonStyle();
        textButtonStyle.up = skin2.getDrawable("button.up");
        textButtonStyle.down = skin2.getDrawable("button.down");
        textButtonStyle.pressedOffsetX = 3;
        textButtonStyle.pressedOffsetX = -3;
        textButtonStyle.font= button;
 
        //Configurations of text field style
        TextFieldStyle textfieldstyle = new TextFieldStyle();
        textboxskin = new Skin();
        uiButton = new Texture(Gdx.files.internal("ui/button.down.png"));
        uiCursor = new Texture(Gdx.files.internal("ui/cursor.png"));
        textboxskin.add("textfieldback", uiButton); 
        textboxskin.add("cursor", uiCursor); 
        textboxskin.add("font", field);
        textfieldstyle.background= textboxskin.getDrawable("textfieldback");
        textfieldstyle.font=textboxskin.getFont("font");
        textfieldstyle.fontColor= com.badlogic.gdx.graphics.Color.WHITE;
        textfieldstyle.cursor= textboxskin.getDrawable("cursor");
        
        sessID = DatabaseManager.getLastSessionID();	//fetches the most recent session ID
        
        //Label instantiations
        titleLabel = new Label("Add Participant",titleSkin);		
        sessionIDLabel = new Label("Session ID", formLabelSkin);	
        playerIDLabel = new Label("Player ID", formLabelSkin);		
       
        //Text field instantiations
        sessionIDField = new TextField(sessID, textfieldstyle);
        sessionIDField.setDisabled(true);
        playerIDField = new TextField ("", textfieldstyle);
       
    	Gdx.input.setInputProcessor(stage);		//attaches input process to current activity

    	//Instantiation and configuration of "Confirm" button
    	confirm = new TextButton("Confirm", textButtonStyle);
    	confirm.addListener(new ChangeListener() {
    		public void changed (ChangeEvent event, Actor actor) {
    			
    			if (playerIDField.getText().equals("")==false){		//if player text field is not empty
    				DatabaseManager.insertPlayer(playerIDField.getText(), sessID);	//insert data in database
    				ScreenManager.getInstance().show("CONTROL_PANEL", Screens.CONTROL_PANEL);	//switch to "Control Panel" activity
    			}
    			else{	//if player text field is empty a dialog box provides the appropriate feedback
    				new Dialog("", skin, "dialog") {
    					protected void result (Object object) {
    					}
    				}.text("Please enter player ID").button("Ok", true).show(stage);
    			}
    		}
    	});
    	
    	//Instantiation and configuration of "Back" button
    	back = new TextButton("Back", textButtonStyle);
    	back.addListener(new ChangeListener() {
    		public void changed (ChangeEvent event, Actor actor) {
    			ScreenManager.getInstance().show("CONTROL_PANEL", Screens.CONTROL_PANEL);	//switch to "Control Panel" activity
    		}
    	});
    	   
    	mainTable = new Table();	//main table instantiation
        mainTable.add(titleLabel);	//attach title label to main table
        mainTable.row();
        
        //Instantiates secondary table and attaches labels, text fields and buttons
        table1 = new Table();	
        table1.add(sessionIDLabel).align(Align.left).spaceRight(Gdx.graphics.getWidth()/75);
        table1.add(sessionIDField).width(sessionIDField.getWidth()*2);
        table1.row();
        
        table1.add(playerIDLabel).align(Align.left).spaceRight(Gdx.graphics.getWidth()/75);
        table1.add(playerIDField).width(sessionIDField.getWidth()*2);
        table1.row();
        
        table1.add(confirm).spaceTop(Gdx.graphics.getWidth()/50).spaceRight(Gdx.graphics.getWidth()/25);
    	table1.add(back).spaceTop(Gdx.graphics.getWidth()/50);
    	
    	mainTable.add(table1);		//attaches secondary table to main table
    	mainTable.pack();
    	
    	//Centers the main table within the screen
    	int xPos = (int) ((Gdx.graphics.getWidth()/2) - (mainTable.getPrefWidth()/2));
    	int yPos = (int) ((Gdx.graphics.getHeight()/2) - (mainTable.getPrefHeight()/2));
    	mainTable.setPosition(xPos, yPos);
    	
    	stage.addActor(ResourceManager.getBackImg());	//attaches background image to stage
    	stage.addActor(mainTable);						//attaches main table to the activity
    }

  
    @Override
    public void render(float delta) {     
        Gdx.gl.glClearColor(0.2f, 0.2f, 0.2f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
    	stage.act(Gdx.graphics.getDeltaTime());
    	stage.draw();
    	Table.drawDebug(stage);
    }

    
	@Override
	public void resize(int width, int height) {
		stage.getViewport().update(width, height, true);	
	}

	
	@Override
	public void show() {}

	
	@Override
	//Disposes resources to mitigate memory leaks
	public void hide() {
		textboxskin.dispose();
		uiButton.dispose();
		uiCursor.dispose();
		button.dispose();
		tLabel.dispose();
		fLabel.dispose();
	    stage.dispose();
	}

	@Override
	public void pause() {}

	
	@Override
	public void resume() {}

	
	@Override
	public void dispose() {}

}

